### ISSUE TITLE
core_1.NgModule is not a function

### ISSUE THREAD

**Issue by mahesh-kedari** [Urigo/meteor-angular2.0-socially#140]
I'm getting and error as 

> card.js:105Uncaught TypeError: core_1.NgModule is not a function

when I try to deploy this app without making any new changes. Any idea if there's some enhancement in angular-meteor core framework which is breaking this functionality?

**Comment by mmccoy** [comment]
Also receiving this, with a fresh clone of the tutorial.  It seems to be coming from angular2-material

**Comment by mahesh-kedari** [comment]
That's right. Its working fine with 2.0.0-alpha.6 version of angular2-material.

**Comment by hhkk** [comment]
Same issue for me :(

After taking the github angular2 socially meteor zip file, I'd changed to the package.json angular RC versions as below to address unmet peer dependency issue, but I was getting this "core_1.NgModule is not a function" error before that as well I believe. 

card.js:105Uncaught TypeError: core_1.NgModule is not a function

"@angular/common": "2.0.0-rc.2"

"@angular/compiler": "2.0.0-rc.2",

"@angular/core": "2.0.0-rc.2",

"@angular/http": "2.0.0-rc.2",

"@angular/platform-browser": "2.0.0-rc.2",

"@angular/platform-browser-dynamic": "2.0.0-rc.2",

**Comment by alecsandruchirosca** [comment]
In my application, the issue is related to 
toolbar.js

In order to solve this issue I used the following package.json:
{
  "name": "angular2-meteor-base",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "meteor test --driver-package practicalmeteor:mocha",
    "test:ci": "meteor test --once --driver-package dispatch:mocha-phantomjs"
  },
  "devDependencies": {
    "chai": "3.5.0",
    "chai-spies": "0.7.1"
  },
  "dependencies": {
    "@angular/common": "https://registry.npmjs.org/@angular/common/-/common-2.0.0-rc.4.tgz",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "https://registry.npmjs.org/@angular/core/-/core-2.0.0-rc.4.tgz",
    "@angular/forms": "https://registry.npmjs.org/@angular/forms/-/forms-0.2.0.tgz",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "3.0.0-alpha.8",
    "@angular2-material/button": "2.0.0-alpha.6",
    "@angular2-material/card": "2.0.0-alpha.6",
    "@angular2-material/checkbox": "2.0.0-alpha.6",
    "@angular2-material/core": "2.0.0-alpha.6",
    "@angular2-material/input": "2.0.0-alpha.6",
    "@angular2-material/toolbar": "2.0.0-alpha.6",
    "angular2-meteor": "0.6.2",
    "angular2-meteor-accounts-ui": "https://registry.npmjs.org/angular2-meteor-accounts-ui/-/angular2-meteor-accounts-ui-0.6.1.tgz",
    "angular2-meteor-auto-bootstrap": "0.6.0",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-meteor-tests-polyfills": "0.0.2",
    "bcrypt": "^0.8.7",
    "es6-shim": "0.35.1",
    "meteor-node-stubs": "0.2.3",
    "ng2-pagination": "^0.3.5",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  }
}

Seems like toolbar.js is using the new RC5 module. Looking forward for the next update.

BR,
Alecs

**Comment by hhkk** [comment]
Thanks. After I synched with the latest example things seem to be going fine.  Perhaps some changes occurred in dependencies.

**Comment by jrosseel** [comment]
Also had this problem. The newest angular-material package migrated to RC5. Which is still incompatible with the current Angular-Meteor release. 

Thanks, your package file fixed it!

**Comment by Urigo** [comment]
Hi everyone and sorry for the late response.
We were hard at work for updating to the latest Angular 2.0 stable.
Please try the new `angular2-meteor@0.7.0`, `angular2-compilers@0.6.3` and the latest Angular 2.0.

We've update the Socially 2.0 tutorial and the Blaze to Angular 2 migration tutorial for reference - https://www.angular-meteor.com/migration/angular2/intro

Sorry for the long wait, it was very hard to keep up with Angular 2 releases in latest months.

If you find issues, please open new ones on the Github repo.
