### ISSUE TITLE
Issue at the end of step 5 with router

### ISSUE THREAD

**Issue by mattlinvilleengler** [Urigo/meteor-angular2.0-socially#108]
<img width="1021" alt="screen shot 2016-06-15 at 11 34 44 pm" src="https://cloud.githubusercontent.com/assets/12705108/16106542/81520780-3352-11e6-9ee1-0f10181dfe5a.png">

**Comment by mattlinvilleengler** [comment]
fixed this compilation error by changing  "as" in routeConfig object to "name". Think this param name must have been switched recently? Now Getting an annotations not found in my browser console though. In tutorial step 5

**Comment by nanomoffet** [comment]
I'm experiencing the same exact problem. I tried switching to name as well with the same result. I even copied the code from the files download at the beginning of step 6 to ensure there's no issue with my code, and it still gets the same error. I reverted to the beginning of step 5, app works fine, by end of step 5 I get this error.

**Comment by mattlinvilleengler** [comment]
@nanomoffet I did the same, downloaded from step 6 and built. Are you getting the annotations error in your console? or still getting the routing error in the meteor cli?

**Comment by mattlinvilleengler** [comment]
@nanomoffet Pretty positive it has something to do with the angular/routing module or the way the routing is being done in the tutorial

**Comment by nanomoffet** [comment]
Same annotations error. Definitely a routing issue though, because the errors appear as soon as the routes are defined - no issues just by importing the router or adding the directives and providers from it.

 I tried swapping in the new angular router but that opened a whole new can of worms.

**Comment by ayush2016** [comment]
I'm facing same issue.

**Comment by jakexconniff** [comment]
Facing same issue, name: replacement did not work for me.

**Comment by nanomoffet** [comment]
I have the new router working in the tutorial project up to 5.12, working on getting the parameters to pass currently. I'll post the code when I have it working. There's not much (read: none) documentation on the new router so it's been a bit difficult to port it, but hopefully once I do it'll allow the rest of the tutorial to progress.

**Comment by nanomoffet** [comment]
Well I still can't get the parameters passed in, but I'll post what I have so far. Maybe someone else can figure out the last bit faster than I can. Note you need to install the npm package @angular/router 3.0.0-alpha.3 if you're still using RC1.

My ongoing issue is in party-details.ts, the code examples for the component router assume data is being pulled as a promise from an angular service, so the setup for getting the parameter from activatedRoute is different.

Edit: I think I discovered the issue, and it actually has to do with more advanced meteor concepts of publishing and subscribing that appears to be handled later in the tutorial. I'm going to try to work on that and I'll edit here if I get it working, but hopefully this will allow basic routing and be enough to proceed with the tutorial.

app.ts

```
import 'reflect-metadata';
import { Component, provide } from '@angular/core';
import { bootstrap } from 'angular2-meteor-auto-bootstrap';
import { APP_ROUTER_PROVIDERS } from './app.routes';
import { APP_BASE_HREF } from '@angular/common';
import { ROUTER_DIRECTIVES } from '@angular/router';


@Component({
  selector: 'app',
  templateUrl: '/client/app.html',
  directives: [ROUTER_DIRECTIVES]
})

class Socially {}

bootstrap(Socially, [ APP_ROUTER_PROVIDERS, provide(APP_BASE_HREF, { useValue: '.' })]);
```

app.routes.ts

```
import { provideRouter, RouterConfig } from '@angular/router';

import { PartiesRoutes } from './parties.routes.ts';

const routes: RouterConfig = [
  ...PartiesRoutes
];

export const APP_ROUTER_PROVIDERS = [
  provideRouter(routes)
];
```

parties.routes.ts

```
import { PartiesList } from './imports/parties-list/parties-list.ts';
import { PartyDetails } from './imports/party-details/party-details.ts';

export const PartiesRoutes = [
  {path: '/', component: PartiesList, index: true},
  {path: '/:partyId', component: PartyDetails }
];
```

parties-list.ts

```
import { Component }   from '@angular/core';
import { Parties }     from '../../../collections/parties';
import { PartiesForm } from '../parties-form/parties-form';
import { Mongo }       from 'meteor/mongo';
import { ROUTER_DIRECTIVES } from '@angular/router';

@Component({
  selector: 'parties-list',
  templateUrl: '/client/imports/parties-list/parties-list.html',
  directives: [PartiesForm, ROUTER_DIRECTIVES]
})
export class PartiesList {
  parties: Mongo.Cursor<Object>;

  constructor() {
    this.parties = Parties.find();
  }

  removeParty(party) {
    Parties.remove(party._id);
  }
}
```

party-details.ts

```
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ROUTER_DIRECTIVES, ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/fromPromise';
import {Parties} from '../../../collections/parties.ts';

@Component({
  selector: 'party-details',
  templateUrl: '/client/imports/party-details/party-details.html',
directives: [ROUTER_DIRECTIVES]
})
export class PartyDetails implements OnInit, OnDestroy {

  constructor(
    private route: ActivatedRoute
  ) { }

  party: Object;

  ngOnInit() {

  }

ngOnDestroy() {

}

}
```

**Comment by nanomoffet** [comment]
I noticed when I got to step 9 that there were other dependencies on the deprecated router now, so on a whim I decided to go back and try the code from the tutorial, and it works just fine after the recent update as long as I make the change from "as" to "name" in the routes. I made sure I'm explicitly using RC1, because I think RC2 had something to do with the issues we were experiencing. Through step 5 (again) and routes with parameters are working flawlessly.

Just a heads up for anyone who hasn't gone back and tried this again.

**Comment by mattlinvilleengler** [comment]
hey @nanomoffet, thanks for all the help - i haven't been able to work on it until now - so basically you just make sure you're using rc-1?

**Comment by nanomoffet** [comment]
RC 1 allowed the deprecated router to work with the change of using Name instead of As in the route definitions. Here's my package.json through step 9.9:

```
{
  "name": "socially",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "angular2-meteor": "0.5.5",
    "angular2-meteor-accounts-ui": "^0.5.0",
    "angular2-meteor-auto-bootstrap": "0.5.5",
    "angular2-meteor-polyfills": "^0.1.1",
    "es6-shim": "0.35.1",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "typings": "^1.3.0",
    "zone.js": "0.6.12"
  }
}
```

And if you'd prefer to try the new router, someone posted a working solution using the component router and meteor's data service here: https://github.com/Urigo/angular2-meteor/issues/301 though you'd still need the deprecated-router installed at least as it's flagged as a dependency by the accounts-ui package.

**Comment by acefed** [comment]
Much appreciated @nanomoffet, your code and remarks helped me a lot: Compilation errors fixed and some routing working with angular/router 3.0.0-alpha.3

Similar dilemma here about the choice of router... this tutorial is turning into a big puzzle :)

**Comment by nanomoffet** [comment]
Yeah, the whole Angular 2 community is in something of limbo thanks to the router business since it's so core to any app. Personally, I finished the tutorial using the deprecated router, and now in an actual project I'm taking another crack at the component router so we'll see how that goes.

**Comment by ayush2016** [comment]
https://github.com/Urigo/meteor-angular2.0-socially/pull/111

**Comment by AlohaTiger** [comment]
I have changed the "@angular/router-deprecated": "2.0.0-rc.1" back to "@angular/router-deprecated": "2.0.0-rc.0".

Now it works well.

**Comment by alexanderwe** [comment]
Hi, @nanomoffet your mention of using RC1 instead of RC2, helped me to get the routing thing to work, thanks a lot! 

Do you recommend to use a newer version when coding a "real" app ?

**Comment by kamilkisiela** [comment]
Socially is now using `@angular/router`.

@mention me if you want to reopen this or something.

**Comment by Quinncuatro** [comment]
I know this is closed, but I was still having the issue. Found a solution [here](http://stackoverflow.com/questions/39692286/meteor-js-routing-on-angular-2-tutorial-doesnt-work).

Basically, party._id is an object, so you need to drill down to that _str in the parties-list.component.html routerLink.
